# Generated by Django 5.0.6 on 2024-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
